//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONPE.WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidato
    {
        public int CandidatoId { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public int PartidoPoliticoId { get; set; }
        public int DistritoId { get; set; }
        public string Estado { get; set; }
    
        public virtual Distrito Distrito { get; set; }
        public virtual PartidoPolitico PartidoPolitico { get; set; }
    }
}
